-- 1. Enable AI
create extension if not exists vector;

-- 2. Create Pages Table
create table pages (
  id bigint generated by default as identity primary key,
  url text unique not null,
  title text,
  status text default 'discovered', -- 'discovered', 'crawled', 'failed'
  last_crawled timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Create Code Snippets Table
create table code_snippets (
  id bigint generated by default as identity primary key,
  page_id bigint references pages(id) on delete cascade,
  language text not null,
  content text not null,
  embedding vector(384),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Create Index for Fast AI Search
create index on code_snippets using ivfflat (embedding vector_cosine_ops)
with (lists = 100);

-- 5. Create Search Function (RPC)
create or replace function search_pages(
  keyword text, 
  match_threshold float default 0.1,
  page_offset int default 0
)
returns table (
  title text,
  url text,
  last_crawled timestamptz,
  rank real
)
language sql
as $$
  SELECT 
    title, 
    url, 
    last_crawled, 
    ts_rank(to_tsvector('english', title), plainto_tsquery('english', keyword)) as rank
  FROM pages
  WHERE status = 'crawled'
  AND (
    to_tsvector('english', title) @@ plainto_tsquery('english', keyword)
    OR 
    url ILIKE '%' || keyword || '%'
  )
  ORDER BY rank DESC, LENGTH(url) ASC
  LIMIT 10
  OFFSET page_offset;
$$;